import fs from 'fs';
import path from 'path';
import { NeutralAgentDef, GeneratedFile } from '../types.js';
import { HarnessAdapter } from './types.js';

const HARNESS_OPEN_TAG = '<!-- qai-harness:start -->';
const HARNESS_CLOSE_TAG = '<!-- qai-harness:end -->';
const AGENTS_FILE = 'AGENTS.md';

function agentSection(def: NeutralAgentDef): string {
  const model = def.models['codex'] ?? def.models['openai'] ?? 'gpt-4o';

  return [
    `## ${def.name}`,
    '',
    `**Description:** ${def.description}`,
    `**Version:** ${def.version}  |  **Model:** ${model}`,
    '',
    '### Memory Access',
    '',
    `Business rules, features, and test conventions are stored in \`${def.memoryPath}/\`.`,
    'Before drafting, read them using shell commands:',
    '',
    '```sh',
    `cat ${def.memoryPath}/rules.md`,
    `cat ${def.memoryPath}/features.md`,
    `cat ${def.memoryPath}/conventions.md`,
    '```',
    '',
    'If those files are empty or missing, draft from the feature description alone.',
    '',
    '### Instructions',
    '',
    def.systemPrompt,
    '',
    '---',
  ].join('\n');
}

function buildHarnessBlock(defs: NeutralAgentDef[]): string {
  const sections = defs.map(agentSection).join('\n\n');
  return `${HARNESS_OPEN_TAG}\n# Agents\n\n<!-- Generated by qai harness — do not edit this block directly. Edit agents/*.md and re-run: qai harness generate --provider codex -->\n\n${sections}\n${HARNESS_CLOSE_TAG}`;
}

export class CodexAdapter implements HarnessAdapter {
  readonly providerTarget = 'codex' as const;

  generate(defs: NeutralAgentDef[], projectRoot: string): GeneratedFile[] {
    const filePath = path.join(projectRoot, AGENTS_FILE);
    let existing = '';
    if (fs.existsSync(filePath)) {
      existing = fs.readFileSync(filePath, 'utf8');
    }

    const harnessBlock = buildHarnessBlock(defs);

    let content: string;
    if (existing.includes(HARNESS_OPEN_TAG)) {
      // Replace the existing harness block, preserve everything else
      content = existing.replace(
        new RegExp(`${HARNESS_OPEN_TAG}[\\s\\S]*?${HARNESS_CLOSE_TAG}`),
        harnessBlock,
      );
    } else {
      // Append the harness block
      content = existing ? `${existing.trimEnd()}\n\n${harnessBlock}\n` : `${harnessBlock}\n`;
    }

    return [{ path: AGENTS_FILE, content }];
  }
}
