import fs from 'fs';
import path from 'path';
import { NeutralAgentDef, GeneratedFile } from '../types.js';
import { HarnessAdapter, resolveTools } from './types.js';

const HARNESS_OPEN_TAG = '<!-- qai-harness:start -->';
const HARNESS_CLOSE_TAG = '<!-- qai-harness:end -->';
const COPILOT_INSTRUCTIONS_FILE = path.join('.github', 'copilot-instructions.md');

function agentSection(def: NeutralAgentDef): string {
  const model = def.models['copilot'] ?? def.models['openai'] ?? 'gpt-4o';
  const nativeTools = resolveTools(def.tools, 'copilot');

  return [
    `## Agent: ${def.name}`,
    '',
    `**Description:** ${def.description}`,
    `**Version:** ${def.version}  |  **Model:** ${model}`,
    nativeTools.length ? `**Tools:** ${nativeTools.join(', ')}` : '',
    '',
    '### Memory',
    '',
    `Client business rules, features, and test conventions are in \`${def.memoryPath}/\`.`,
    'Use the Read tool (or file access) to load the relevant client subfolder before responding.',
    '',
    `- \`${def.memoryPath}/<client>/rules.md\``,
    `- \`${def.memoryPath}/<client>/features.md\``,
    `- \`${def.memoryPath}/<client>/conventions.md\``,
    '',
    'If those files are absent or empty, draft from the provided feature description alone.',
    '',
    '### Instructions',
    '',
    def.systemPrompt,
    '',
    '---',
  ]
    .filter((l) => l !== null)
    .join('\n');
}

function buildHarnessBlock(defs: NeutralAgentDef[]): string {
  const sections = defs.map(agentSection).join('\n\n');
  return `${HARNESS_OPEN_TAG}\n# Copilot Workspace Instructions\n\n<!-- Generated by qai harness — do not edit this block directly. Edit agents/*.md and re-run: qai harness generate --provider copilot -->\n\n${sections}\n${HARNESS_CLOSE_TAG}`;
}

export class CopilotAdapter implements HarnessAdapter {
  readonly providerTarget = 'copilot' as const;

  generate(defs: NeutralAgentDef[], projectRoot: string): GeneratedFile[] {
    const filePath = path.join(projectRoot, COPILOT_INSTRUCTIONS_FILE);
    let existing = '';
    if (fs.existsSync(filePath)) {
      existing = fs.readFileSync(filePath, 'utf8');
    }

    const harnessBlock = buildHarnessBlock(defs);

    let content: string;
    if (existing.includes(HARNESS_OPEN_TAG)) {
      content = existing.replace(
        new RegExp(`${HARNESS_OPEN_TAG}[\\s\\S]*?${HARNESS_CLOSE_TAG}`),
        harnessBlock,
      );
    } else {
      content = existing ? `${existing.trimEnd()}\n\n${harnessBlock}\n` : `${harnessBlock}\n`;
    }

    return [{ path: COPILOT_INSTRUCTIONS_FILE, content }];
  }
}
